### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: extend must be a string

### ISSUE THREAD

**Issue by andrewgbliss** [googleapis/nodejs-logging-bunyan#563]
Node Version: 14.17.5
NPM Version: 6.14.14
@google-cloud/logging-bunyan Version:  3.1.1

```
UnhandledPromiseRejectionWarning: TypeError: extend must be a string
at new Field (/usr/src/app/node_modules/protobufjs/src/field.js:79:15)
at fromJSON (/usr/src/app/node_modules/protobufjs/src/field.js:38:12)
at fromJSON (/usr/src/app/node_modules/protobufjs/src/type.js:247:31)
at Namespace.addJSON (/usr/src/app/node_modules/protobufjs/src/namespace.js:182:39)
at fromJSON (/usr/src/app/node_modules/protobufjs/src/namespace.js:36:46)
at Namespace.addJSON (/usr/src/app/node_modules/protobufjs/src/namespace.js:182:39)
at fromJSON (/usr/src/app/node_modules/protobufjs/src/namespace.js:36:46)
at Root.addJSON (/usr/src/app/node_modules/protobufjs/src/namespace.js:182:39)
at Function.fromJSON (/usr/src/app/node_modules/protobufjs/src/root.js:51:17)
at new LoggingServiceV2Client (/usr/src/app/node_modules/@google-cloud/logging/build/src/v2/logging_service_v2_client.js:171:62)
at new Logging (/usr/src/app/node_modules/@google-cloud/logging/build/src/index.js:132:31)
at new LoggingBunyan (/usr/src/app/node_modules/@google-cloud/logging-bunyan/build/src/index.js:149:31)
at Object.<anonymous> (/usr/src/app/api/src/utils/queue/queue_jobs/createJob.js:20:23)
at Module._compile (internal/modules/cjs/loader.js:1072:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
at Module.load (internal/modules/cjs/loader.js:937:32)
at Function.Module._load (internal/modules/cjs/loader.js:778:12)
at Module.require (internal/modules/cjs/loader.js:961:19)
at require (internal/modules/cjs/helpers.js:92:18)
at Object.<anonymous> (/usr/src/app/api/src/utils/queue/queue_jobs/index.js:1:23)
at Module._compile (internal/modules/cjs/loader.js:1072:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
```

Code that I am running, this is the only instance of the LoggingBunyan I am creating:

```
const bunyan = require('bunyan');
const { LoggingBunyan } = require('@google-cloud/logging-bunyan');

// Creates a Bunyan Cloud Logging client
const loggingBunyan = new LoggingBunyan();

// Create a Bunyan logger that streams to Cloud Logging
// Logs will be written to: "projects/YOUR_PROJECT_ID/logs/bunyan_log"
const loggerBunyan = bunyan.createLogger({
  // The JSON payload of the log as it appears in Cloud Logging
  // will contain "name": "my-service"
  name: 'local_queue_logs',
  streams: [
    // Log to the console at 'info' and above
    { stream: process.stdout, level: 'info' },
    // And log to Cloud Logging, logging at 'info' and above
    loggingBunyan.stream('info'),
  ],
});
```

**Comment by minherz** [comment]
Thank you for reporting the problem.
Can you confirm that the above code represents a minimal program that reproducing the problem?

**Comment by andrewgbliss** [comment]
It is not a minimal program, however that is the code from the readme that I am trying to integrate into our production system.

**Comment by minherz** [comment]
Andrew, we are happy to help. In a sake of time saving, would it be possible to ask you to confirm that running just this code yields the above error? Or there are additional logging activities should be in place?

**Comment by andrewgbliss** [comment]
I added the middleware to my express app and that part works. However when trying to add this code into the project it gives this error. So I want to be able to log in the express app and other places in the app, like utility functions.

I would assume that running just this code only works, it's taken right from the example in this repo.

**Comment by losalex** [comment]
@andrewgbliss, sorry it took time to get back to you - I used an example you shared and was unable to repro this specific problem. Please let me know if you still facing this issue and if yes, I would be happy to get from you more details on reproducing this problem.
